version: '3.8'

services:
  postgres:
    container_name: odoo-postgres
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_USER: ${PG_USER}
      PGDATA: /var/lib/postgresql/data/odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/odoo/
    ports:
      - 5432:5432/tcp

  odoo:
    container_name: odoo-frontend
    image: odoo:14.0
    restart: always
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - 8069:8069/tcp

  nginx:
    container_name: odoo-proxy-pass
    image: nginx:latest
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - odoo
    restart: always
    links:
      - odoo:odoo

volumes:
  odoo-db-data:
  odoo-web-data:
