version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_USER: ${PG_USER}
      PGDATA: /var/lib/postgresql/data/odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/odoo/
    ports:
      - 5432:5432/tcp

# pgadmin is now optional
#   pgadmin:
#     image: dpage/pgadmin4:5.4
#     restart: always
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin
#     ports:
#       - 5050:80/tcp
#     links:
#       - postgres:postgres
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
#       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
#     depends_on:
#       - postgres

  odoo:
    build: .
    restart: always
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - 8069:8069/tcp

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - odoo
    restart: always
    links:
      - odoo:odoo
#       - pgadmin:pgadmin

# ngrok is now optional
#   ngrok:
#     image: wernight/ngrok:latest
#     ports:
#       - 4040:4040
#     environment:
#       NGROK_PROTOCOL: http
#       NGROK_PORT: nginx:80
#       NGROK_AUTH: ${NGROK_AUTH}
#     depends_on:
#       - nginx

volumes:
  odoo-db-data:
  odoo-web-data:
#   pgadmin-data:
